- repo: local
  hooks:
      - id: format
        name: format
        entry: make format
        language: system
        types: [python]
      - id: lint
        name: flake8
        entry: make lint
        language: system
        types: [python]
